### ISSUE TITLE
Propose to rename TAB3 to Teaching Assistant’s Buddy

### ISSUE THREAD

**Issue by tanjoewel** [AY2122S1-CS2103-F09-1/tp#40]
Given that TAB3 might mess with the grading script, I propose we spell out the name instead and ditch the level-3 component

**Comment by charliemoweng** [comment]
Agree

**Comment by WangGLJoseph** [comment]
Agreed!

**Comment by Ruofan1023** [comment]
yep. From what I have found we probably also need to edit content in these docs:

1. README.md
![image](https://user-images.githubusercontent.com/69947227/135554302-473dc694-55c3-4f93-8112-e1d2cc8cf461.png)

2. docs/index.md
![image](https://user-images.githubusercontent.com/69947227/135554320-30d7eb9c-0858-4d05-b10e-7e93dc1c6417.png)

**Comment by Ruofan1023** [comment]
Some other traces of AB3 that I have identified. Can someone update them if they have time in order to make sure we can pass all the checks?

1. NFR point 2 does not seem to fit our app
![Screenshot_2021-10-01-18-58-51-276_com.github.android.jpg](https://user-images.githubusercontent.com/69947227/135609640-b6b54fc9-59a4-4593-8d6b-f9b32a575f0d.jpg)

2. Target user profile bullet point 1 does not fit our app
![Screenshot_2021-10-01-18-58-28-433_com.github.android.jpg](https://user-images.githubusercontent.com/69947227/135609761-60024f61-d748-47d3-a946-996163523aad.jpg)

3. In user guide, the name is still address book
![Screenshot_2021-10-01-18-57-54-738_com.github.android.jpg](https://user-images.githubusercontent.com/69947227/135609853-c0258db2-0e49-49c8-9a24-471c8bb74ee0.jpg)

FYI these are the issues we still need to resolve 
![Screenshot_2021-10-01-18-59-37-227_com.android.chrome.jpg](https://user-images.githubusercontent.com/69947227/135609993-39371b64-3176-4d5d-b97f-598add0a76dd.jpg)
